### ISSUE TITLE
配置分组

### ISSUE THREAD

**Issue by weiding9527** [polarismesh/website#357]
配置中心，新增并发布配置文件，点击“发布”会报错内容过长：
![image](https://github.com/polarismesh/website/assets/95093935/f8e94083-e1f9-45f8-bbd5-edfd985ef2ae)
请问这个上限默认是多大？支持修改这个上限吗？

**Comment by chuntaojun** [comment]
目前是2w字符上线，我们在1.17.2新增了这个配置，去调整 polaris-server.yaml 即可

```yaml
# Configuration center module start configuration
config:
  # Whether to start the configuration module
  open: true
  # Maximum number of number of file characters
  contentMaxLength: 20000
```
